[package]
name = "central-server"
version = "0.0.1"
edition = "2021"

[lib]
name = "server"
path = "src/lib.rs"

[[bin]]
name = "server"
path = "src/main.rs"

[dependencies]
common = { path = "../common/" }
axum = "0.1.0"
